[WIP]Feature/Graphical PRM modeling
OpenTOSCA/winery pull request #224
Opened 2020-11-24 08:29 UTC by bjoernmu

Graphical PRM modeling with the topologymodeler

TODO:
-get possible Mappings as Relationshiptypes
-show information in sidebar

- [x] Ensure that you followed http://eclipse.github.io/winery/dev/ToolChain#github---prepare-pull-request.
- [x] Branch name checked. That means, the branch name starts with `thesis/`, `fix/`, ...
- [x] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Ensure to use auto format in **all** files
- [x] Ensure that you appear in `NOTICE` at Copyright Holders
- [ ] Tests created for changes
- [ ] Documentation updated (if needed)
- [ ] Screenshots added (for UI changes)

2021-01-27 13:18 UTC, lharzenetter requested changes

2021-01-27 13:18 UTC, lharzenetter commented on org.eclipse.winery.frontends/app/topologymodeler/src/app/canvas/canvas.component.ts
> +    selectedRelationshipType: EntityType = new EntityType('', '', '', '');
Wouldn't it be easier to just use a default constructor?

2021-01-27 13:18 UTC, lharzenetter commented on org.eclipse.winery.frontends/package-lock.json
> +    "version": "2.0.0-SNAPSHOT",
this looks like a wrong merge

2021-01-27 13:18 UTC, lharzenetter commented on org.eclipse.winery.frontends/package-lock.json
> +            "version": "2.0.4",
dito

2021-01-27 13:18 UTC, lharzenetter commented on org.eclipse.winery.frontends/package.json
> +    "version": "2.0.0-SNAPSHOT",
see package.lock.json

2021-02-09 15:45 UTC, bjoernmu commented
Follow up at https://github.com/eclipse/winery/pull/556

2021-02-09 15:45 UTC, closed without merging